from __future__ import annotations

from typing import Any, Protocol


class ToolExecutor(Protocol):
    def call(self, name: str, args: dict[str, Any]) -> list[dict[str, Any]]: ...


class ChatHistory(Protocol):
    def create_session(self, title: str, ts: str) -> int: ...
    def add_message(self, session_id: int, ts: str, role: str, content: str, model: str | None = None,
                    tool_calls: list[dict[str, Any]] | None = None, duration_ms: int | None = None) -> int: ...
    def list_sessions(self, search: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
    def get_session(self, session_id: int) -> dict[str, Any] | None: ...
    def delete_session(self, session_id: int) -> bool: ...
    def export_markdown(self, session_id: int) -> str: ...

