from __future__ import annotations

from typing import Protocol, Sequence

from domain.knowledge import KnowledgeChunk, RetrievedChunk


class EmbeddingProvider(Protocol):
    model: str
    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class KnowledgeStore(Protocol):
    def initialize(self) -> None: ...
    def cached_embeddings(self, source_uri: str, embedding_model: str) -> dict[str, list[float]]: ...
    def replace_source(self, source_uri: str, chunks: list[KnowledgeChunk], embeddings: list[list[float] | None] | None,
                       embedding_model: str | None, ts: str) -> dict[str, int]: ...
    def lexical_search(self, query: str, trust_levels: tuple[str, ...], limit: int) -> list[RetrievedChunk]: ...
    def vector_candidates(self, trust_levels: tuple[str, ...], limit: int = 2000) -> list[tuple[RetrievedChunk, list[float]]]: ...
    def audit_rag(self, ts: str, query_hash: str, route: str, ids: list[int], embedding_model: str | None,
                  duration_ms: int) -> None: ...
    def knowledge_status(self) -> dict[str, object]: ...
