from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from domain.models import AlertCandidate, CollectionResult, EvidenceView


class CollectionRepository(Protocol):
    def initialize(self) -> None: ...
    def start_run(self, kind: str, started_at: str, is_admin: bool) -> int: ...
    def save_collection(self, run_id: int, result: CollectionResult, now: str) -> int: ...
    def finish_run(self, run_id: int, finished_at: str, status: str, collectors: dict[str, Any]) -> None: ...
    def get_cursor(self, source: str) -> dict[str, Any] | None: ...
    def status(self) -> dict[str, Any]: ...
    @property
    def database_path(self) -> Path: ...


class AnalysisRepository(Protocol):
    def initialize(self) -> None: ...
    def start_run(self, kind: str, started_at: str, is_admin: bool) -> int: ...
    def finish_run(self, run_id: int, finished_at: str, status: str, collectors: dict[str, Any]) -> None: ...
    def load_evidence(self, since: str) -> EvidenceView: ...
    def save_alerts(self, candidates: list[AlertCandidate]) -> list[int]: ...
    def get_new_alerts(self, limit: int = 500) -> list[dict[str, Any]]: ...
    def save_llm_analysis(self, run_id: int, ts: str, model: str, alert_ids: list[int], prompt_chars: int, result: dict[str, Any] | None, error: str | None, duration_ms: int) -> None: ...
    def update_alert_status(self, alert_id: int, status: str, note: str | None, ts: str) -> None: ...
    def approve_baseline(self, kind: str, value: str, ts: str) -> None: ...
    def observe_baseline(self, view: EvidenceView, ts: str, approve: bool = False) -> None: ...
    def count_runs(self, kind: str) -> int: ...
