from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from domain.models import CollectionResult


class CollectionRepository(Protocol):
    def initialize(self) -> None: ...
    def start_run(self, kind: str, started_at: str, is_admin: bool) -> int: ...
    def save_collection(self, run_id: int, result: CollectionResult, now: str) -> int: ...
    def finish_run(self, run_id: int, finished_at: str, status: str, collectors: dict[str, Any]) -> None: ...
    def get_cursor(self, source: str) -> dict[str, Any] | None: ...
    def status(self) -> dict[str, Any]: ...
    @property
    def database_path(self) -> Path: ...

